export enum TaskActionTypes {
	ADD_TASK = "ADD_TASK",
	DELETE_TASK = "DELETE_TASK",
	CREATE_TASK = "CREATE_TASK",
	SELECT_TASK = "SELECT_TASK",
	SEARCH_TASK = "SEARCH_TASK",
	UPDATE_TASK = "UPDATE_TASK",
	OPEN_FORM_TASK = "OPEN_FORM_TASK",
}
